title: Práctica 4
email: alu0101283197@ull.edu.es
description: >- # this means to ignore newlines until "baseurl:"
  WebComponent
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  Felipe5Valencia

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  - character